In [1]:
import sys,os,re
import pandas as pd
import scipy.stats as stats

Delimiter = '\t'

In [2]:
df = pd.read_csv("/orange/soltis/shan158538/Methylation_output/feature_methylation/gbm_ANOVA/gbm_CHH_shared_loci.txt", sep=Delimiter)

In [3]:
df

,Tdu_bin_0,Tdu_bin_1,Tdu_bin_2,Tdu_bin_3,Tdu_bin_4,Tdu_bin_5,Tdu_bin_6,Tdu_bin_7,Tdu_bin_8,Tdu_bin_9,...,Tms_bin_50,Tms_bin_51,Tms_bin_52,Tms_bin_53,Tms_bin_54,Tms_bin_55,Tms_bin_56,Tms_bin_57,Tms_bin_58,Tms_bin_59
0,0.067743,0.054785,0.064063,0.066967,0.064294,0.060979,0.075056,0.067709,0.055684,0.060664,...,0.068237,0.067173,0.060337,0.065926,0.060531,0.062558,0.063437,0.065283,0.05941,0.049337
1,0.073972,0.070743,0.073634,0.085174,0.081619,0.076503,0.083407,0.081390,0.068362,0.071381,...,0.067993,0.065598,0.058141,0.064884,0.056835,0.058759,0.059985,0.060473,0.05544,0.046812

In [4]:
for bin_id in range(0,60):
    Tdu = f'Tdu_bin_{bin_id}'
    Tpr = f'Tpr_bin_{bin_id}'
    Tms = f'Tms_bin_{bin_id}'
    fvalue, pvalue = stats.f_oneway(df[Tdu], df[Tpr], df[Tms])
    print ("For bin:", bin_id, pvalue)

For bin: 0 0.05006346882915999
For bin: 1 0.5743614489917408
For bin: 2 0.7986287056872527
For bin: 3 0.8442429306395406
For bin: 4 0.8604753836972896
For bin: 5 0.9565273477152932
For bin: 6 0.9983649821549971
For bin: 7 0.3899006881946588
For bin: 8 0.7216569434255811
For bin: 9 0.8097906521488393
For bin: 10 0.22685002412355515
For bin: 11 0.011670710256557594
For bin: 12 0.6581975121573611
For bin: 13 0.9634637604672935
For bin: 14 0.11942423781611099
For bin: 15 0.2766470110871001
For bin: 16 0.7603401289070205
For bin: 17 0.43656080946997866
For bin: 18 0.6295981275608538
For bin: 19 0.02726306480121783
For bin: 20 0.3096566818895066
For bin: 21 0.2091037598468358
For bin: 22 0.3646945884862729
For bin: 23 0.3333900032353839
For bin: 24 0.5098084956285291
For bin: 25 0.7398297436978241
For bin: 26 0.8764930992022388
For bin: 27 0.9443018674179947
For bin: 28 0.9747824834503492
For bin: 29 0.9680482443630711
For bin: 30 0.9431894284100188
For bin: 31 0.9873935446114833
For bin: 32 0.8666427141937803
For bin: 33 0.948172732731122
For bin: 34 0.9620861933578239
For bin: 35 0.8930023334424718
For bin: 36 0.9131417796030609
For bin: 37 0.8722400281179505
For bin: 38 0.8522371983852832
For bin: 39 0.7076833208306945
For bin: 40 0.5367623072935505
For bin: 41 0.25172340921580144
For bin: 42 0.4579046000695919
For bin: 43 0.509167983154365
For bin: 44 0.06790679277657227
For bin: 45 0.17329375021687832
For bin: 46 0.7892971235037664
For bin: 47 0.23933663811651115
For bin: 48 0.22869875853523647
For bin: 49 0.2862685878261278
For bin: 50 0.9206804156165774
For bin: 51 0.7177403349991057
For bin: 52 0.7670082397158879
For bin: 53 0.7931244748396201
For bin: 54 0.22031993333014532
For bin: 55 0.7160537604672387
For bin: 56 0.8879665957339595
For bin: 57 0.5692247374361895
For bin: 58 0.9710812895614942
For bin: 59 0.36757656286307655