In [1]:
import sys,os,re
import pandas as pd
import scipy.stats as stats

Delimiter = '\t'

In [2]:
df = pd.read_csv("/orange/soltis/shan158538/Methylation_output/feature_methylation/gbm_ANOVA/gbm_CHG_shared_loci.txt", sep=Delimiter)

In [3]:
df

,Tdu_bin_0,Tdu_bin_1,Tdu_bin_2,Tdu_bin_3,Tdu_bin_4,Tdu_bin_5,Tdu_bin_6,Tdu_bin_7,Tdu_bin_8,Tdu_bin_9,...,Tms_bin_50,Tms_bin_51,Tms_bin_52,Tms_bin_53,Tms_bin_54,Tms_bin_55,Tms_bin_56,Tms_bin_57,Tms_bin_58,Tms_bin_59
0,0.483086,0.541347,0.591057,0.482854,0.465011,0.525178,0.477575,0.450797,0.416810,0.358661,...,0.405223,0.367052,0.422897,0.375685,0.390083,0.326513,0.396517,0.392450,0.381846,0.337362
1,0.417446,0.498746,0.524349,0.460472,0.445438,0.492283,0.425687,0.378452,0.409378,0.332607,...,0.377994,0.345039,0.401074,0.350377,0.379358,0.294336,0.358155,0.363045,0.338374,0.292972

In [4]:
for bin_id in range(0,60):
    Tdu = f'Tdu_bin_{bin_id}'
    Tpr = f'Tpr_bin_{bin_id}'
    Tms = f'Tms_bin_{bin_id}'
    fvalue, pvalue = stats.f_oneway(df[Tdu], df[Tpr], df[Tms])
    print ("For bin:", bin_id, pvalue)

For bin: 0 0.17697453415700026
For bin: 1 0.16028676608923645
For bin: 2 0.43849750031188767
For bin: 3 0.1454787577155992
For bin: 4 0.026425166048806598
For bin: 5 0.07753565680221247
For bin: 6 0.20606912865723134
For bin: 7 0.4044277569697442
For bin: 8 0.057780828360924116
For bin: 9 0.29948826376889914
For bin: 10 0.038104937934563175
For bin: 11 0.023807244023281958
For bin: 12 0.021857103856629614
For bin: 13 0.14832071535287905
For bin: 14 0.13957596781071016
For bin: 15 0.08192448640449476
For bin: 16 0.08599427361119995
For bin: 17 0.3075633426475574
For bin: 18 0.2505207753959342
For bin: 19 0.3389204452113629
For bin: 20 0.10908044447008386
For bin: 21 0.11746200535699639
For bin: 22 0.18745303918166345
For bin: 23 0.14522089006554506
For bin: 24 0.21067871468514351
For bin: 25 0.4024441458544387
For bin: 26 0.41482105799376745
For bin: 27 0.33374635731218955
For bin: 28 0.3763365767837872
For bin: 29 0.3077307533773099
For bin: 30 0.2880295389883938
For bin: 31 0.36991149621219943
For bin: 32 0.24932145020691523
For bin: 33 0.2570513853297239
For bin: 34 0.24845878682485467
For bin: 35 0.25873348750765235
For bin: 36 0.1803961980115239
For bin: 37 0.15401161569704197
For bin: 38 0.18115553306524126
For bin: 39 0.12744379443972423
For bin: 40 0.4326353427407526
For bin: 41 0.11272219691541864
For bin: 42 0.3082127018463757
For bin: 43 0.2636396077953998
For bin: 44 0.1254253686202357
For bin: 45 0.10801183102909531
For bin: 46 0.4199434989428938
For bin: 47 0.18172935065288096
For bin: 48 0.3821835965142613
For bin: 49 0.48404436982855703
For bin: 50 0.5807494531447374
For bin: 51 0.14841515715219258
For bin: 52 0.3513665485360237
For bin: 53 0.30064309168631304
For bin: 54 0.31609936510217146
For bin: 55 0.7025205345033898
For bin: 56 0.07110998584051907
For bin: 57 0.04490179462057548
For bin: 58 0.233135547342032
For bin: 59 0.04543591644315034